spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library?useUnicode=true&serverTimezone=UTC
    username: root
    password: MsVasl5!
    driver-class-name: com.mysql.cj.jdbc.Driver
  #Show sql logs
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
  servlet:
    context-path: /demo

test:
  field: "value"